### ISSUE TITLE
Add support for destroying screentime instance

### ISSUE THREAD

**Issue by nandita121189** [robflaherty/screentime#6]
I have a situation where I need to reinitialize screentime within a different html on same page(without refresh). Now when I initialize screentime for the second time, the looker and reporter instances  generated during the first call still are intact and not destroyed, due to which the old loops are also going on along with the new loops. And similarly when this happens for third time, more loops are constantly getting added up unnecessarily.

**Comment by robflaherty** [comment]
Hi - Yes, I agree, this needs to be added :)

**Comment by robflaherty** [comment]
@nandita121189 I added a reset method to this dev branch. Can you try it and let me know if it works for you?

This just resets the timers. (Do you also need to initialize new DOM elements?) 
`$.screentime.reset()`

https://github.com/robflaherty/screentime/tree/reset-method

**Comment by nandita121189** [comment]
Thanks for the fix. :)
Yes, it works for me. And no i don't need to initialize new DOM elements right now.

**Comment by robflaherty** [comment]
Thanks for testing it out. I added the feature to the master branch.
